create table MASTER_PROVINCES
(
    ID   NUMBER(19) not null
        primary key,
    NAME VARCHAR2(255 char),
    RANK VARCHAR2(255 char)
)
/

INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (1, 'Thành phố Hà Nội', 'Thành phố Trung ương', '01', 1, 'Bac', 'Hà Nội', 'THANH PHO HA NOI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (2, 'Tỉnh Hà Giang', 'Tỉnh', '02', 2, 'Bac', 'Hà Giang', 'TINH HA GIANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (4, 'Tỉnh Cao Bằng', 'Tỉnh', '04', 3, 'Bac', 'Cao Bằng', 'TINH CAO BANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (6, 'Tỉnh Bắc Kạn', 'Tỉnh', '06', 4, 'Bac', 'Bắc Kạn', 'TINH BAC KAN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (8, 'Tỉnh Tuyên Quang', 'Tỉnh', '08', 5, 'Bac', 'Tuyên Quang', 'TINH TUYEN QUANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (10, 'Tỉnh Lào Cai', 'Tỉnh', '10', 6, 'Bac', 'Lào Cai', 'TINH LAO CAI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (11, 'Tỉnh Điện Biên', 'Tỉnh', '11', 7, 'Bac', 'Điện Biên', 'TINH DIEN BIEN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (12, 'Tỉnh Lai Châu', 'Tỉnh', '12', 8, 'Bac', 'Lai Châu', 'TINH LAI CHAU');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (14, 'Tỉnh Sơn La', 'Tỉnh', '14', 9, 'Bac', 'Sơn La', 'TINH SON LA');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (15, 'Tỉnh Yên Bái', 'Tỉnh', '15', 10, 'Bac', 'Yên Bái', 'TINH YEN BAI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (17, 'Tỉnh Hòa Bình', 'Tỉnh', '17', 11, 'Bac', 'Hòa Bình', 'TINH HOA BINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (19, 'Tỉnh Thái Nguyên', 'Tỉnh', '19', 12, 'Bac', 'Thái Nguyên', 'TINH THAI NGUYEN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (20, 'Tỉnh Lạng Sơn', 'Tỉnh', '20', 13, 'Bac', 'Lạng Sơn', 'TINH LANG SON');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (22, 'Tỉnh Quảng Ninh', 'Tỉnh', '22', 14, 'Bac', 'Quảng Ninh', 'TINH QUANG NINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (24, 'Tỉnh Bắc Giang', 'Tỉnh', '24', 15, 'Bac', 'Bắc Giang', 'TINH BAC GIANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (25, 'Tỉnh Phú Thọ', 'Tỉnh', '25', 16, 'Bac', 'Phú Thọ', 'TINH PHU THO');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (26, 'Tỉnh Vĩnh Phúc', 'Tỉnh', '26', 17, 'Bac', 'Vĩnh Phúc', 'TINH VINH PHUC');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (27, 'Tỉnh Bắc Ninh', 'Tỉnh', '27', 18, 'Bac', 'Bắc Ninh', 'TINH BAC NINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (30, 'Tỉnh Hải Dương', 'Tỉnh', '30', 19, 'Bac', 'Hải Dương', 'TINH HAI DUONG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (31, 'Thành phố Hải Phòng', 'Thành phố Trung ương', '31', 20, 'Bac', 'Hải Phòng', 'THANH PHO HAI PHONG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (33, 'Tỉnh Hưng Yên', 'Tỉnh', '33', 21, 'Bac', 'Hưng Yên', 'TINH HUNG YEN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (34, 'Tỉnh Thái Bình', 'Tỉnh', '34', 22, 'Bac', 'Thái Bình', 'TINH THAI BINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (35, 'Tỉnh Hà Nam', 'Tỉnh', '35', 23, 'Bac', 'Hà Nam', 'TINH HA NAM');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (36, 'Tỉnh Nam Định', 'Tỉnh', '36', 24, 'Bac', 'Nam Định', 'TINH NAM DINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (37, 'Tỉnh Ninh Bình', 'Tỉnh', '37', 25, 'Bac', 'Ninh Bình', 'TINH NINH BINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (38, 'Tỉnh Thanh Hóa', 'Tỉnh', '38', 26, 'Trung', 'Thanh Hóa', 'TINH THANH HOA');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (40, 'Tỉnh Nghệ An', 'Tỉnh', '40', 27, 'Trung', 'Nghệ An', 'TINH NGHE AN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (42, 'Tỉnh Hà Tĩnh', 'Tỉnh', '42', 28, 'Trung', 'Hà Tĩnh', 'TINH HA TINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (44, 'Tỉnh Quảng Bình', 'Tỉnh', '44', 29, 'Trung', 'Quảng Bình', 'TINH QUANG BINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (45, 'Tỉnh Quảng Trị', 'Tỉnh', '45', 30, 'Trung', 'Quảng Trị', 'TINH QUANG TRI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (46, 'Tỉnh Thừa Thiên Huế', 'Tỉnh', '46', 31, 'Trung', 'Thừa Thiên Huế', 'TINH THUA THIEN HUE');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (48, 'Thành phố Đà Nẵng', 'Thành phố Trung ương', '48', 32, 'Trung', 'Đà Nẵng', 'THANH PHO DA NANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (49, 'Tỉnh Quảng Nam', 'Tỉnh', '49', 33, 'Trung', 'Quảng Nam', 'TINH QUANG NAM');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (51, 'Tỉnh Quảng Ngãi', 'Tỉnh', '51', 34, 'Trung', 'Quảng Ngãi', 'TINH QUANG NGAI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (52, 'Tỉnh Bình Định', 'Tỉnh', '52', 35, 'Trung', 'Bình Định', 'TINH BINH DINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (54, 'Tỉnh Phú Yên', 'Tỉnh', '54', 36, 'Trung', 'Phú Yên', 'TINH PHU YEN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (56, 'Tỉnh Khánh Hòa', 'Tỉnh', '56', 37, 'Trung', 'Khánh Hòa', 'TINH KHANH HOA');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (58, 'Tỉnh Ninh Thuận', 'Tỉnh', '58', 38, 'Trung', 'Ninh Thuận', 'TINH NINH THUAN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (60, 'Tỉnh Bình Thuận', 'Tỉnh', '60', 39, 'Trung', 'Bình Thuận', 'TINH BINH THUAN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (62, 'Tỉnh Kon Tum', 'Tỉnh', '62', 40, 'Trung', 'Kon Tum', 'TINH KON TUM');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (64, 'Tỉnh Gia Lai', 'Tỉnh', '64', 41, 'Trung', 'Gia Lai', 'TINH GIA LAI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (66, 'Tỉnh Đắk Lắk', 'Tỉnh', '66', 42, 'Trung', 'Đắk Lắk', 'TINH DAK LAK');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (67, 'Tỉnh Đắk Nông', 'Tỉnh', '67', 43, 'Trung', 'Đắk Nông', 'TINH DAK NONG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (68, 'Tỉnh Lâm Đồng', 'Tỉnh', '68', 44, 'Trung', 'Lâm Đồng', 'TINH LAM DONG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (70, 'Tỉnh Bình Phước', 'Tỉnh', '70', 45, 'Nam', 'Bình Phước', 'TINH BINH PHUOC');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (72, 'Tỉnh Tây Ninh', 'Tỉnh', '72', 46, 'Nam', 'Tây Ninh', 'TINH TAY NINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (74, 'Tỉnh Bình Dương', 'Tỉnh', '74', 47, 'Nam', 'Bình Dương', 'TINH BINH DUONG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (75, 'Tỉnh Đồng Nai', 'Tỉnh', '75', 48, 'Nam', 'Đồng Nai', 'TINH DONG NAI');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (77, 'Tỉnh Bà Rịa - Vũng Tàu', 'Tỉnh', '77', 49, 'Nam', 'Bà Rịa - Vũng Tàu', 'TINH BA RIA - VUNG TAU');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (79, 'Thành phố Hồ Chí Minh', 'Thành phố Trung ương', '79', 50, 'Nam', 'TP.Hồ Chí Minh', 'THANH PHO HO CHI MINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (80, 'Tỉnh Long An', 'Tỉnh', '80', 51, 'Nam', 'Long An', 'TINH LONG AN');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (82, 'Tỉnh Tiền Giang', 'Tỉnh', '82', 52, 'Nam', 'Tiền Giang', 'TINH TIEN GIANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (83, 'Tỉnh Bến Tre', 'Tỉnh', '83', 53, 'Nam', 'Bến Tre', 'TINH BEN TRE');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (84, 'Tỉnh Trà Vinh', 'Tỉnh', '84', 54, 'Nam', 'Trà Vinh', 'TINH TRA VINH');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (86, 'Tỉnh Vĩnh Long', 'Tỉnh', '86', 55, 'Nam', 'Vĩnh Long', 'TINH VINH LONG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (87, 'Tỉnh Đồng Tháp', 'Tỉnh', '87', 56, 'Nam', 'Đồng Tháp', 'TINH DONG THAP');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (89, 'Tỉnh An Giang', 'Tỉnh', '89', 57, 'Nam', 'An Giang', 'TINH AN GIANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (91, 'Tỉnh Kiên Giang', 'Tỉnh', '91', 58, 'Nam', 'Kiên Giang', 'TINH KIEN GIANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (92, 'Thành phố Cần Thơ', 'Thành phố Trung ương', '92', 59, 'Nam', 'Cần Thơ', 'THANH PHO CAN THO');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (93, 'Tỉnh Hậu Giang', 'Tỉnh', '93', 60, 'Nam', 'Hậu Giang', 'TINH HAU GIANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (94, 'Tỉnh Sóc Trăng', 'Tỉnh', '94', 61, 'Nam', 'Sóc Trăng', 'TINH SOC TRANG');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (95, 'Tỉnh Bạc Liêu', 'Tỉnh', '95', 62, 'Nam', 'Bạc Liêu', 'TINH BAC LIEU');
INSERT INTO VDSMS.MASTER_PROVINCES (ID, NAME, RANK, CODE, ORIGIN_ID, REGIONS, SHORT_NAME, SIGNLESS_NAME) VALUES (96, 'Tỉnh Cà Mau', 'Tỉnh', '96', 63, 'Nam', 'Cà Mau', 'TINH CA MAU');