create table MASTER_NATIONS
(
    ID   NUMBER(19) not null
        primary key,
    NAME VARCHAR2(255 char)
)
/

INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (1, 'Kinh');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (2, 'Tày');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (3, 'Thái');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (4, 'Hoa');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (5, 'Khơ-me');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (6, 'Mường');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (7, 'Nùng');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (8, 'HMông');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (9, 'Dao');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (10, 'Gia-rai');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (11, 'Ngái');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (12, 'Ê-đê');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (13, 'Ba na');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (14, 'Xơ-Đăng');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (15, 'Sán Chay');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (16, 'Cơ-ho');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (17, 'Chăm');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (18, 'Sán Dìu');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (19, 'Hrê');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (20, 'Mnông');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (21, 'Ra-glai');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (22, 'Xtiêng');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (23, 'Bru-Vân Kiều');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (24, 'Thổ');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (25, 'Giáy');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (26, 'Cơ-tu');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (27, 'Gié Triêng');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (28, 'Mạ');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (29, 'Khơ-mú');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (30, 'Co');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (31, 'Tà-ôi');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (32, 'Chơ-ro');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (33, 'Kháng');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (34, 'Xinh-mun');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (35, 'Hà Nhì');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (36, 'Chu ru');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (37, 'Lào');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (38, 'La Chí');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (39, 'La Ha');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (40, 'Phù Lá');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (41, 'La Hủ');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (42, 'Lự');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (43, 'Lô Lô');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (44, 'Chứt');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (45, 'Mảng');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (46, 'Pà Thẻn');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (47, 'Co Lao');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (48, 'Cống');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (49, 'Bố Y');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (50, 'Si La');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (51, 'Pu Péo');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (52, 'Brâu');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (53, 'Ơ Đu');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (54, 'Rơ măm');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (55, 'Người nước ngoài');
INSERT INTO VDSMS.MASTER_NATIONS (ID, NAME) VALUES (56, 'Không rõ');